version: '3.8'

services:
  api:
    build: .
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SERVER_MODE: ${SERVER_MODE}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DBNAME: ${PG_DBNAME}
      API_KEY: ${API_KEY}
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./startup.sql:/docker-entrypoint-initdb.d/startup.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
